version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - echo Running tests...
      - echo "Skipping actual Jest tests (for AWS pipeline validation)"
      - exit 0
